### ISSUE TITLE
Resolution borked

### ISSUE THREAD

**Issue by callumrichardson123** [sizlo/SwingGame#2]
On small low res screens the game window is too large and not re sizable, this makes the game a bit weird to play as you are unable to view the full game screen.

It should be possible to change the game window size or be able to make it full screened.

**Comment by sizlo** [comment]
Some game options can now be read from the file config.xml, this includes window dimensions.

Fixed in commit 07419925c2dd4e66516a52070680185a4f0dc03b

It should be noted that the game will always render at 1024*768 and changing the window size will just stretch/compress the image.

**Comment by sizlo** [comment]
Fullscreen is now supported in the config file. And by default the game preserves it's 4:3 aspect ratio no matter what window size you give it.

Commit 3e1eb297b03be92c5a082071b2eeb0a1d143d6b5
